import type { Metadata } from "next";

import { options } from "../api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import { fetchUserDetail } from "../lib/action";
import DashNav from "../ui/dashboard/DashNav";
import DashCardWrapper from "../ui/dashboard/DashCardWrapper";
import { Suspense } from "react";
import LineChartSkeleton from "../ui/dashboard/LineChartSkeleton";
import ChartWrapper from "../ui/dashboard/ChartWrapper";
import Link from "next/link";
import DashLink from "../ui/dashboard/DashLinks";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  let userDetails;
  if (session) {
    userDetails = await fetchUserDetail();
  }

  console.log(userDetails?.totalMatches, userDetails?.totalDuration);
  return (
    <div className="flex flex-col bg-slate-400 drop-shadow-2xl shadow-2xl  min-h-screen md:mx-48 ">
      <DashNav
        session={session}
        totalMatches={userDetails?.totalMatches}
        totalDuration={userDetails?.totalDuration}
        registrationDate={userDetails?.registrationDate}
      />
      {/* flex justify-center gap-4  flex-wrap mb-16  */}
      <div className="flex justify-evenly flex-wrap my-16 gap-8 bg-gray-800 p-8 drop-shadow-2xl rounded-md">
        {userDetails && <DashCardWrapper userDetails={userDetails} />}
      </div>
      <DashLink />

      <main>{children}</main>
    </div>
  );
}
